### PR TITLE
Add vue debounce functionality

### LINKED ISSUE #60: Add support for debounce
I've tried to add debouncing to the search function but the component will not update after the results array is updated. I also tried to call the handleUpdate and handleShow methods directly which will show the results appropriately but clicking on any result fails to populate the event with the result object. Is there any way to update the control after a debounced API call completes? Thanks.

### PR DESCRIPTION
**Pull request by jssouders**
Closes #60

### CODE REVIEW

**Comment by trevoreyre** [comment]
@jssouders - Thanks a lot for taking a crack at this. Overall it looks great. I'd like to move the functionality to the core package so it can be utilized by both the Vue and JavaScript components, and then add an example or two to the docs to demonstrate the functionality. If that's something you'd like to attempt, feel free. Otherwise I'll try to knock it out tomorrow morning or early next week and publish a new release.

**Comment by bryanbassett** [comment]
By the way, I compiled this branch and I'm going to use it - it works great. Thanks guys.

**Comment by jssouders** [comment]
@trevoreyre Originally I tried to add it to the core package, but it appears that debounce has to be implemented on the event listeners at the component level.  If there is a way to do this in the core package it would be a better solution, but I wasn't able to get it to work.

**Comment by jssouders** [comment]
@trevoreyre @bryanbassett On a side note, do you guys know how to reference the forked version of this package until the PR is complete?  I have tried the following based on a couple blog posts but with no luck.

**npm package:**
```
"@trevoreyre/autocomplete-vue": "jssouders/autocomplete#add-vue-debounce",
```

**Results in the following error:**
```
> @ postinstall /Users/jsouders/Git/GitHub/nitro-web/node_modules/@trevoreyre/autocomplete-vue
> lerna bootstrap

sh: lerna: command not found
```
I have also tried checking the dist folders into the forked repo after being built locally, but I still get the same issue.  Is there another way to package this that I am missing?

**Comment by trevoreyre** [comment]
@jssouders - Ah, okay. We may need to just duplicate the functionality in both Vue and JS components then.

As for installing your fork, I'm not super familiar with using GitHub repos directly in npm dependencies. But I think if you add it to your `package.json` as you have, it will be pointing to the root of the directory, which is not actually where the Vue component is. So I think when you import it you'd probably have to do something like `import Autocomplete from '@trevoreyre/autocomplete-vue/packages/autocomplete-vue'` to get to the actual root of the Vue component. Then you'll probably have to run the build command and commit the `dist` folder to your repo because that folder isn't published to GitHub atm. Finally, it looks like the error you're seeing is from the `"postinstall": "lerna bootstrap"` script in the root `package.json`, so you'll probably have to remove that script in your repo as well. Then maybe it will work?

**Comment by trevoreyre** [comment]
@jssouders, @bryanbassett I added debounce to the JS component and modified a couple things. I just need to update a couple spots in the docs and I think this is ready to go. Do you want to try it out to make sure everything works for you?

**Comment by jssouders** [comment]
@trevoreyre Thanks!

**Pull request merged**
